version: '3.4'

services:
  parloa:
    image: moeidheidari/parloa:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parloa
    restart: always
    ports:
      - 8077:${NODE_PORT}
    environment:
      - NODE_ENV=  ${NODE_ENV}
      - NODE_PORT= ${NODE_PORT}
      - PARLOA_LAT= ${PARLOA_LAT}
      - PARLOA_LONG= ${PARLOA_LONG}