version: '3.3'

services:
  grover:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - 8077:8077
    environment:
      - NODE_ENV=  ${NODE_ENV}
      - NODE_PORT= ${NODE_PORT}
      - PARLOA_LAT= ${PARLOA_LAT}
      - PARLOA_LONG= ${PARLOA_LONG}